### ISSUE TITLE
Errors in v. 3.4

### ISSUE THREAD

**Issue by olufine** [tematres/TemaTres-Vocabulary-Server#80]
Hi, We just tried to install version 3.4., but  the GUI doesn't come up, only text. 
It appears that all  CSS comes with "httpss" in stead of "https". Could you please correct this as soon as possible?

**Comment by tematres** [comment]
Hi @olufine we let's to check this, but:
1. In the 3.4 version you can use CDN or not to call the JS and CSS libraries. You can turn on or off the CDN in main config file allocated in common/include/config.tematres.php, the param is:
//Define is use or not CDN to bootstrap and other external libraries, default == false (0)
$CFG["USE_CDN"]=0;

This config file is for all the instances of tematres created in the same server (you can have many instances with one core). You can change this param in the local config file allocated in vocab/config.tematres.php. For example:
//Define is use or not CDN to bootstrap and other external libraries, default == false (0)
$CFG["USE_CDN"]=1;

2. By default, in Tematres 3.4 the CDN's use is dissabled. When the CDN is disable, Tematres use the configured base URL, may be your BASE URL begin with "httpss" instead of "https". You can check that in the footer of your installation (or in URL_YOUR_VOCAB/sobre.php page) . To change the base URL in Menu -> Administration-> Configuration:


I will be hearing the (good or bad) news about this :)

**Comment by olufine** [comment]
The good new (for you) is that the error stemmed from an earlier time at which we ran TemaTres on a  virtual server. Sorry for troubling you about this.

**Comment by tematres** [comment]
OK :)!
